services:
  postgres-test:
    image: postgres
    container_name: postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 151919
      POSTGRES_DB: tests
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  backend:
    container_name: backend-test
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - mynetwork
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run test:ci
      "

networks:
  mynetwork:
