name: CI - Testes com Docker Compose (v2 syntax)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Verificar versão do Docker
        run: docker --version

      - name: Verificar versão do Compose
        run: docker compose version

      - name: Rodar testes com Docker Compose
        run: docker compose -f docker-compose-test.yml up --build --abort-on-container-exit

      - name: Verificar logs do Postgres se erro
        if: failure()
        run: docker logs postgres-test || true
