name: CI - Testes com Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build and Run Test Environment
        run: docker-compose -f docker-compose-test.yml up --build --abort-on-container-exit

      - name: Check Postgres logs (se erro)
        if: failure()
        run: docker logs postgres-test || true
