name: CI/CD Back-end

on:
  push:
    branches:
      - master
      - main

jobs:
  run-tests:
    name: 🧪 Testes automatizados
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 151919
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://postgres:151919@localhost:5432/test_db
      JWT_SECRET: testsecret

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm run test

  build-and-push:
    name: 🐳 Build e Push Docker
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e push da imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: natemaciel/bingo-backend:latest

  deploy-render:
    name: 🚀 Deploy automático no Render
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Disparar webhook de deploy
        run: curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
